### ISSUE TITLE
download.py error

### ISSUE THREAD

**Issue by Mstkj** [acmbpdc/openlib.cs#12]
When running download.py, the script stops due to an error described below:

File "download.py", line 39, in <module>
    download_link = f"""https://drive.google.com/uc?id={par["id"][0]}&export=download"""
KeyError: 'id'

**Comment by neeteshbhati** [comment]
I tried replicating the error and found that the Google Drive URL format has changed in the readme files after the course CS F211. The keyerror exception is caused due to missing key "id" in the dictionary "par". Thanks for bringing this to notice. A hotfix is on the way.

**Comment by neeteshbhati** [comment]
Updated the download script and readme files for CS F111 and CS F211. The issue is fixed.
