### ISSUE TITLE
Mkdocs + Vercel

### ISSUE THREAD

**Issue by cricksmaidiene** [acmbpdc/openlib.cs#14]
`CC: @kelvindecosta @Mohammed-Shoaib `

This repository has been around a while, and at the time I believe there was a [github pages](https://acmbpdc.github.io/openlib.cs/) deployment as well as a [gitbook](https://bpdc-acm.gitbook.io/openlib-cs/courses) deployment that we tried out. Since all the courses are markdown files anyway, I wonder if it's worth having a fully deployed [mkdocs](https://squidfunk.github.io/mkdocs-material/) site, probably using [vercel](https://vercel.com/)? We can setup [github actions](https://docs.github.com/en/actions) to take new commits and deploy them automatically.

**Comment by kelvindecosta** [comment]
There's a GitHub pages deployment from the markdown.
Can use a Jekyll template instead of mkdocs.
Since it's already hosted on GitHub pages, we don't need Vercel.
