### ISSUE TITLE
No content for CS > Electives > Number Theory (CSF231)

### ISSUE THREAD

**Issue by Fir121** [acmbpdc/openlib.cs#16]
**Describe the solution you'd like**
Need to fill in content for this course

**Describe alternatives you've considered**
Remove if this course is no longer offered by BITS?

**Comment by abxhr** [comment]
`OpenLib.cs` is not just exclusive to the courses at BITS, but courses in the domain of Computer Science itself.
Nonetheless, I believe *Number Theory* is still offered as an elective at BITS. 
Hence, we could add content to the `README` of this course. 
Feel free to create a PR for the same! 🙌
