### ISSUE TITLE
Fix GitHub Pages Deployment

### ISSUE THREAD

**Issue by abxhr** [acmbpdc/openlib.cs#19]
- [x] Use custom domain instead of `github.io`
- [x] Find a good theme for the deployment (*`mkdocs` of `jekyll`*)
- [x] Setup an environment for CD to the website

**Comment by anuragkj** [comment]
I went through some themes and really like the "Material" theme. Looks clean and proffesional.

**Comment by datdhruv** [comment]
Site Published @ https://openlib-cs.acmbpdc.org/
