### ISSUE TITLE
Links Legibility in Dark Theme

### ISSUE THREAD

**Issue by AhmedThahir** [acmbpdc/openlib.cs#28]
**Describe the bug**
Links are not very legible in dark theme, as there is not enough contrast between color of the link and the background.

**To Reproduce**
1. Go to any page with a link
2. Switch page to dark theme
3. Look at the link

**Expected behavior**

Higher contrast. Maybe brighten the link color?

**Screenshots**

![image](https://user-images.githubusercontent.com/94914628/230760167-d4fec0fa-4cd6-4b8f-8b68-4e684b71d87c.png)

**Additional Detail**

Using online [contrast checker tool ](https://webaim.org/resources/contrastchecker/)

![image](https://user-images.githubusercontent.com/94914628/230760367-424b8214-3d2d-4f91-922f-a0147f1a9f47.png)

**Comment by abxhr** [comment]
@AhmedThahir Thank you for opening this issue! We'll look into this 🙌
